In [1]:
import numpy as np
    
def corrTimeAndSpace(t1 = None,t2 = None,s1 = None,s2 = None,varargin = None): 
    # varargout = corrTimeAndSpace(t1,t2,s1,s2,varargin)
    
    # Correlate two decompositions using both the timecourses (t1 and t2) and
# spatial profiles (s1 and s2).
    
    # 2018 - Adam Charles
    
    ###########################################################################
## Input parsing
    
    if len(varargin) > 4:
        thresh_t = varargin[0]
    else:
        thresh_t = 0.1
    
    if len(varargin) > 5:
        thresh_s = varargin[2]
    else:
        thresh_s = 0.5
    
    if len(varargin) > 6:
        thresh_pix = varargin[3]
    else:
        thresh_pix = 0.1
    
    s1 = reshape(s1,[],s1.shape[np.asarray(s1).ndim-1])
    
    s2 = reshape(s2,[],s2.shape[np.asarray(s2).ndim-1])
    
    if (np.shape(s1[:,1]) != np.shape(t1[:,1])) or (np.shape(s2[:,1]) != np.shape(t2[:,1])):
        raise Exception('Must have matching number of spatial and temporal components.')
    
    if (np.shape(t1[:,1]) != np.shape(t1[:,1])) or (np.shape(s1[:,1]) != np.shape(s2[:,1])):
        raise Exception('Must have matching dimensions for spatial/temporal components.')
    
    ###########################################################################
## Calculate temporal correlations and
    
    s1 = np.greater(s1,thresh_pix * np.amax(s1,[],1))
    s1.astype(int)
    
    s2 = np.greater(s2,thresh_pix * np.amax(s2,[],1))
    s2.astype(int)
    
    tp1 = np.sum(s1, 1)
    tp2 = np.sum(s2, 1)
    olap = (np.transpose(s1)) * single(s2)
    
    C = np.corrcoef(np.array([t1,t2]))
    
    C = C(0:np.shape(t1[:,1]),(np.shape(t1[:,1]) + 1:end))
    
    C[C < thresh_t] = NaN
    
    C[np.logical_and[[np.divide(olap, tp2) < thresh_s],[np.divide(olap, np.transpose(tp1)) < thresh_s]]] = NaN
    
    if nargout > 2:
        varargout[3] = C
    
    corr_vec = []
    
    all_pairs = []
    
    while np.any(not np.isnan(C) ):

        cm = np.amax(C(not np.isnan(C) ))
        I,J = find(C == cm,1,'first')
        corr_vec = np.concatenate(1,corr_vec,cm)
        all_pairs = np.concatenate(1,all_pairs,np.array([I,J]))
        C[:,J] = NaN

    
    ###########################################################################
## Output parsing
    
    if nargout == 1:
        tmp.corrs = corr_vec
        tmp.pairs = all_pairs
        varargout[0] = tmp
    else:
        if nargout > 1:
    return varargout
    
###########################################################################
###########################################################################
    
# C(olap<thresh_s) = NaN;                                                    # Threshold correlations for non-sufficiently-overlapping profiles
# olap = bsxfun(@rdivide, olap, sum(s2,1));                                  # Normalize to the number of total pixels in s2
# C    = t1.'*t2;                                                            # Calculate (temporal) correlation matrix


In [36]:
A = np.zeros((4,2))
print(A)
A[0,0] = 8
A[1,0] = 8
A[2,0] = 8
A[3,0] = 8


np.shape(A[:,1])

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


(4,)

In [28]:
B = np.zeros((1,3))
print(B)

[[0. 0. 0.]]


In [32]:
C = np.greater(A,B)
print(C)
C.astype(int)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])